name: PMK-BungeeUtils
main: fr.pmk_bungeeutils.MainBungeeUtils
version: 1.0
author: Clem_Fern

commands:
  blockmod:
    description: Commande controlant le blockage
    usage: /blockmod
    
  support:
    description:  Commande de demande de support
  
  ensupport:  
    description:  Commande d activation de la visibilite ou non
    